  apiVersion: karpenter.sh/v1
  kind: NodePool
  metadata:
    name: default
  spec:
    template:
      spec:
        nodeClassRef:
          group: karpenter.k8s.aws
          name: default
          kind: EC2NodeClass
        expireAfter: 720h
        requirements:
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["spot"]
          - key: "kubernetes.io/arch"
            operator: In
            values: ["arm64", "amd64"]
    limits:
      # resources:
      cpu: "1000"
    disruption:
      consolidationPolicy: WhenEmptyOrUnderutilized
      consolidateAfter: 1m
---
  apiVersion: karpenter.k8s.aws/v1
  kind: EC2NodeClass
  metadata:
    name: default
  spec:
    amiFamily: AL2
    role: KarpenterNodeRole-opfleet 
    subnetSelectorTerms:
      - tags:
        karpenter.sh/discovery: opfleet 
    securityGroupSelectorTerms:
      - tags:
        karpenter.sh/discovery: opfleet 